### ISSUE TITLE
"Subindex does not exist" when trying to run separate_thread.py

### ISSUE THREAD

**Issue by AKAMEDIASYSTEM** [ngblume/ethercat-pysoem#1]
Hi, thank you for sharing your work!

I'm trying to use pysoem to talk to an EL4008 and have simplified your `simple_thread.py` script (just removing references to other Beckhoff units, not adding any code).

Unfortunately I'm unable to get the script to run; each time during the `config_map()` step I get an `SdoError` indicating the library is trying to write to register 0x1c13 - this will fail on units like the EL4008 and the EL4104 becuase they do not accept writes to that address (a Beckhoff rep was able to reproduce the same error code for me by trying this write in TwinCAT).

I'm now looking into the underlying C SOEM library to determine where the write is happening, but wondered if you had come across this issue when you were getting `separate_thread.py` working, since you use an EL4008 in your original code?

Any help or ideas would be much appreciated, although I understand you haven't worked on this repo in a little while - thanks for sharing what you made, regardless!

AKA

PS, my version of your `separate_thread.py` is [here](https://github.com/AKAMEDIASYSTEM/ethercatscratch/blob/master/separate_thread.py)

**Comment by ngblume** [comment]
Hej AKA,

so sorry first of all..
I never got any notice of your issue being posted.. I just came across it by accident now...
Don't know if my answer will be of any help anymore, but I will give it anyway.. 
Let me know, if I can help any other way..

I never had an issue with that python script when I ran it, especially not with the EL4008s..
When checking the documentation, the index "0x1c13" appers to be "Tx PDO Assign" with regards to "Sync Manager 3 (Outputs)". Index "0x1c12" would be "Rx PDO Assign" with regards to "Sync Manager 2 (Inputs)".
That this object is not writable on an EL4008 is logical, since the EL4008 hast a static PDO mapping (pg. 167, c h. 5.5 in https://download.beckhoff.com/download/Document/io/ethercat-terminals/EL40xxen.pdf).

The issues you see, might be related to the distributed clock, since there is a dependency of the sync managers on the sync mode (Free Run, SM-Synchronous, etc..)
see EtherCAT poster at https://www.ethercat.org/download/documents/EtherCAT_Device_Protocol_Poster.pdf

I do not see any reason, why ConfigMap should try to **write** to this object. Reading seems somewhat plausible, since it needs to build the memory map including assigned Rx/Tx PDOs. Especially, since you can see in the screenshot at the beginning of chapter 5.5, that the mapping for the RxPDOs for the EL4008 (to which you write the requested voltage) are listed in object 0x1C12:
![image](https://github.com/ngblume/ethercat-pysoem/assets/3869392/686f5021-4902-4d21-a6c6-483f054b8103)
I do not understand the inner workings of the Sync Manager, but I think you might be doing something there by accident...

There are some steps required for the EL2872 (see ch. 5.5 in https://download.beckhoff.com/download/Document/io/ethercat-terminals/EL28xxen.pdf) along DC clocks and Sync Manager and objects 0x1C12 and 0x1C13...
Do you have something in your code regarding distributed clocks or sync at all (and maybe by accident effecting the EL4008) ??

Cheers
Niels Göran

**Comment by AKAMEDIASYSTEM** [comment]
Thank you so much for your thoughtful response! I believe I "solved" this problem by ignoring the SdoError and continuing on with the script (rather than braking and exiting the script upon that error occurring). 

...definitely not as helpful as finding out what the root cause of the issue was, but my application ran reliably and continuously for many months, so I believe it is generally safe to ignore the error.

Thanks again for following up!

AKA
